//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ProjectStatus = &struct {
	Registering postgres.StringExpression
	Progressing postgres.StringExpression
	Finished    postgres.StringExpression
}{
	Registering: postgres.NewEnumValue("registering"),
	Progressing: postgres.NewEnumValue("progressing"),
	Finished:    postgres.NewEnumValue("finished"),
}
