//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type PaymentHistory struct {
	ID        int64 `sql:"primary_key"`
	ProjectID uuid.UUID
	Amount    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
}
