//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Project struct {
	ID          uuid.UUID `sql:"primary_key"`
	UserID      uuid.UUID
	Name        *string
	Description *string
	Price       *int32
	Status      ProjectStatus
	StartTime   *time.Time
	EndTime     *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
