//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Profile = newProfileTable("public", "profile", "")

type profileTable struct {
	postgres.Table

	// Columns
	UserID    postgres.ColumnString
	FirstName postgres.ColumnString
	LastName  postgres.ColumnString
	ImageURL  postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz
	UpdatedAt postgres.ColumnTimestampz
	About     postgres.ColumnString
	Phone     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ProfileTable struct {
	profileTable

	EXCLUDED profileTable
}

// AS creates new ProfileTable with assigned alias
func (a ProfileTable) AS(alias string) *ProfileTable {
	return newProfileTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ProfileTable with assigned schema name
func (a ProfileTable) FromSchema(schemaName string) *ProfileTable {
	return newProfileTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ProfileTable with assigned table prefix
func (a ProfileTable) WithPrefix(prefix string) *ProfileTable {
	return newProfileTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ProfileTable with assigned table suffix
func (a ProfileTable) WithSuffix(suffix string) *ProfileTable {
	return newProfileTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newProfileTable(schemaName, tableName, alias string) *ProfileTable {
	return &ProfileTable{
		profileTable: newProfileTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newProfileTableImpl("", "excluded", ""),
	}
}

func newProfileTableImpl(schemaName, tableName, alias string) profileTable {
	var (
		UserIDColumn    = postgres.StringColumn("user_id")
		FirstNameColumn = postgres.StringColumn("first_name")
		LastNameColumn  = postgres.StringColumn("last_name")
		ImageURLColumn  = postgres.StringColumn("image_url")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn = postgres.TimestampzColumn("updated_at")
		AboutColumn     = postgres.StringColumn("about")
		PhoneColumn     = postgres.StringColumn("phone")
		allColumns      = postgres.ColumnList{UserIDColumn, FirstNameColumn, LastNameColumn, ImageURLColumn, CreatedAtColumn, UpdatedAtColumn, AboutColumn, PhoneColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, FirstNameColumn, LastNameColumn, ImageURLColumn, CreatedAtColumn, UpdatedAtColumn, AboutColumn, PhoneColumn}
	)

	return profileTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		UserID:    UserIDColumn,
		FirstName: FirstNameColumn,
		LastName:  LastNameColumn,
		ImageURL:  ImageURLColumn,
		CreatedAt: CreatedAtColumn,
		UpdatedAt: UpdatedAtColumn,
		About:     AboutColumn,
		Phone:     PhoneColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
